### ISSUE TITLE
Arbre binaire: Object.keys[] ne fonctionne pas

### ISSUE THREAD

**Issue by PierreTurnbull** [yamsellem/hetic.js#1]
tree[Object.keys(tree)[1]] et tree[Object.keys(tree)[2]] ne permette pas à mon programme de fonctionner correctement.
Je me suis rendu compte en lisant la solution qu'en écrivant tree.right et tree.left, mon programme passait le test sans problème. (je partais du principe qu'on ne sait pas forcément comme s'appellent les branches de l'arbre).
Paste bin du js: https://www.pastiebin.com/5a25773e9b260

**Comment by yamsellem** [comment]
Le problème vient du fait que la variable `tree` contient trois clés.

```javascript
var tree = {
  value: 8, 
  left: {value: 3, left: {value: 1}, right: {value: 6}}, 
  right: {value: 11, right: {value: 14}}
};

Object.keys(tree); // returns ["value", "left", "right"]
```
