### ISSUE TITLE
Ajax > premier exo: impossible de faire quoi que ce soit!

### ISSUE THREAD

**Issue by PierreTurnbull** [yamsellem/hetic.js#4]
Au premier exo du chapitre Ajax, "Rechercher un repository github", impossible de faire quoi que ce soit, aucun bouton ne marche, y compris le bouton "vérifier". Je suis coincé et ne peux pas en sortir. Je précise qu'en ouvrant une précédente version du MOOC la page s'ouvre sur cet exercice, donc impossible de faire quoi que ce soit.

**Comment by yamsellem** [comment]
Salut Pierre,


J'ai introduit un bug dans ce chapitre il y'a quelques temps.

Peux-tu essayer avec la dernière version de app.js sur github, de mémoire,
j'ai réparé le problème depuis.
--
yves

**Comment by PierreTurnbull** [comment]
yes ça marche. merci

2018-02-05 19:18 GMT+01:00 Yves Amsellem <notifications@github.com>:
